export const nftData = [
	{
		title: "EEG Scan",
		desc: "My EEG scan in active attentive state as a 20 years old healthy male.",
		price: "0.1",
		type: "EEG",
		image: "https://via.placeholder.com/500x200",
		id: "1",
	},
	{
		title: "Stanford Neuroimaging Study",
		desc: "Stanford Study taken between 2018-2020, having gathered neural data from more than 5000 patients.",
		price: "0.2",
		type: "art",
		image: "https://via.placeholder.com/500x200",
		id: "2",
	},
	{
		title: "EEG Collection",
		desc: "Dataset of over 40 EEG scans taken from volunteers with OpenBCI hardware.",
		price: "Free",
		type: "art",
		image: "https://via.placeholder.com/500x200",
		id: "3",
	},
	{
		title: "NFT Title 4",
		desc: "Biomedical study taken on more than 50 patiens under 30 years old.",
		price: "0.2",
		type: "art",
		image: "https://via.placeholder.com/500x200",
		id: "4",
	},
	{
		title: "NFT Title 5",
		desc: "Biomedical study taken on more than 50 patiens under 30 years old.",
		price: "0.2",
		type: "art",
		image: "https://via.placeholder.com/500x200",
		id: "5",
	},
	{
		title: "Stanford Neuroimaging Study",
		desc: "Biomedical study taken on more than 50 patiens under 30 years old.",
		price: "0.2",
		type: "art",
		image: "https://via.placeholder.com/500x200",
		id: "6",
	},
	{
		title: "Biomedical study - 30 people",
		price: "0.2",
		type: "art",
		image: "https://via.placeholder.com/500x200",
		id: "7",
	},
	{
		title: "Biomedical study - 30 people",
		price: "0.2",
		type: "art",
		image: "https://via.placeholder.com/500x200",
		id: "8",
	},
];
